# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/config.ipynb.

# %% auto 0
__all__ = ['ConfigMaeLarge', 'ConfigVQVAE']

# %% ../nbs/config.ipynb 2
class ConfigMaeLarge:
    seed = 1000

    model_name = "vitmae_fb_large_v5"
    prev_model_name = None

    img_size = 256
    in_chans = 3
    lr = 1e-4
    bs = 8
    epochs = 2
    weight_decay = 0.05
    betas = (0.9, 0.95)

    gpus = [0]
    num_gpus = len(gpus)

    embd_dim = 256

    # Masked AutoEncoder Params
    encoder_embedding_dim = embd_dim
    depth_enc = 24
    num_heads_enc = 16

    decoder_embedding_dim = 128
    decoder_depth = 8
    decoder_num_heads = 16

    mlp_ratio = 4.0

    patch_size = 8
    mask_ratio = 0.75

    DATA_DIR = "../data/"
    IMG_DIR = DATA_DIR + "cars_dataset/"
    MODELS_DIR = "../models/"

    TRAINING_LOGS_DIR = f"../training_logs/{model_name}/"
    CHECKPOINTS_DIR = TRAINING_LOGS_DIR + "checkpoints/"

    TRAINING_RECON_IMG_DIR = f"{TRAINING_LOGS_DIR}{model_name}/"

    embedding_name = "final2"
    EMBEDDINGS_DIR = DATA_DIR + "embeddings/"
    EMBEDDING_COL_NAMES = [f"dim_{k}" for k in range(encoder_embedding_dim)]
    EMBEDDING_FILE_PATH = (
        f"{EMBEDDINGS_DIR}{model_name}_{encoder_embedding_dim}_{embedding_name}.csv"
    )

    size_val = 0.2  # Size of validation set

# %% ../nbs/config.ipynb 5
class ConfigVQVAE:
    seed = 1000

    DATA_DIR = "../data/"
    IMG_DIR = DATA_DIR + "cars_dataset/"
    MODELS_DIR = "../models/"

    img_size = 256

    gpus = [0]
    num_gpus = len(gpus)

    # Training Params
    lr = 1e-3
    bs = 64
    epochs = 100
    size_val = 0.2  # Size of validation set

    embd_dim = 2048

    if embd_dim == 512:
        training_name = "16_16_2_v1"
        num_layers = (
            4  # number of downsamples - ex. 256 / (2 ** 3) = (32 x 32 feature map)
        )
    else:
        training_name = "32_32_2_v2"
        num_layers = (
            3  # number of downsamples - ex. 256 / (2 ** 3) = (32 x 32 feature map)
        )

    # Model Config
    model_name = f"dalle_vq_vae_{training_name}"

    num_tokens = 8192  # number of visual tokens. in the paper, they used 8192, but could be smaller for downsized projects
    codebook_dim = 2  # codebook dimension
    hidden_dim = 128  # hidden dimension
    num_resnet_blocks = 2  # number of resnet blocks
    use_vq_commit_loss = True

    # Logging
    TRAINING_LOGS_DIR = f"../training_logs/{model_name}/"
    TRAINING_RECON_IMG_DIR = f"{TRAINING_LOGS_DIR}{model_name}/"
    CHECKPOINTS_DIR = f"{TRAINING_LOGS_DIR}checkpoints/"

    # Embeddings
    EMBEDDINGS_DIR = DATA_DIR + "embeddings/"
    EMBEDDING_FILE_PATH = f"{EMBEDDINGS_DIR}{model_name}_{embd_dim}.csv"
    EMBEDDING_COL_NAMES = [f"dim_{k}" for k in range(embd_dim)]
